services:
  - type: web
    name: panotic
    runtime: node
    rootDir: backend
    buildCommand: npm install && npx prisma generate && npx prisma migrate deploy && npm run build
    startCommand: npm start
    envVars:
      - key: DATABASE_URL
        value: postgresql://panotic_db_user:aI5Bri3nTnhVqAlGGZW1I24IEuzVkwvi@dpg-d8i8c6btqb8s73at1q9g-a/panotic_db
      - key: JWT_SECRET
        value: panotic_jwt_secret_2024_tres_securise_xK9mP3qR
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
