import { Platform, Dimensions, StyleSheet } from 'react-native';
import { COLORS } from '../constants/colors';

const { width, height } = Dimensions.get('window');

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: COLORS.background },
  map: { flex: 1 },
  loadingOverlay: {
    ...StyleSheet.absoluteFillObject,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(255,255,255,0.6)',
    zIndex: 999,
  },
  topBar: {
    position: 'absolute',
    top: 0, left: 0, right: 0,
    zIndex: 100,
    backgroundColor: COLORS.primary,
    paddingTop: Platform.OS === 'ios' ? 50 : 10,
    paddingBottom: 10,
    paddingHorizontal: 15,
    elevation: 10,
  },
  topBarTitle: {
    color: COLORS.white,
    fontSize: 18,
    fontWeight: 'bold',
    textAlign: 'center',
  },
  searchContainer: {
    position: 'absolute',
    top: Platform.OS === 'ios' ? 100 : 60,
    left: 15, right: 15,
    zIndex: 200,
    elevation: 20,
  },
  searchContainerFocused: {
    left: 0, right: 0,
    top: Platform.OS === 'ios' ? 95 : 55,
  },
  searchBox: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: COLORS.white,
    borderRadius: 12,
    paddingHorizontal: 15,
    height: 46,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 5,
  },
  searchBoxFocused: {
    borderRadius: 0,
    height: 52,
    paddingHorizontal: 20,
    shadowOpacity: 0.15,
    shadowRadius: 12,
    elevation: 8,
  },
  searchInput: { flex: 1, marginLeft: 10, fontSize: 15, color: COLORS.text, outlineStyle: 'none' },
  searchInputFocused: { fontSize: 16 },
  searchResults: {
    backgroundColor: COLORS.white,
    borderRadius: 8,
    marginTop: 5,
    maxHeight: 200,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 5,
  },
  searchResultItem: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 12,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.border,
  },
  searchResultText: { marginLeft: 10, fontSize: 14, color: COLORS.text },
  layerTabs: {
    position: 'absolute',
    top: Platform.OS === 'ios' ? 155 : 115,
    left: 15, right: 15,
    zIndex: 100,
    elevation: 10,
  },
  layerScroll: { flexDirection: 'row' },
  layerTab: {
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderRadius: 20,
    backgroundColor: COLORS.white,
    marginRight: 8,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.08,
    shadowRadius: 4,
    elevation: 3,
    flexDirection: 'row',
    alignItems: 'center',
  },
  activeTab: { backgroundColor: COLORS.primary },
  tabText: {
    fontSize: 13,
    fontWeight: '700',
    color: COLORS.textSecondary,
    marginLeft: 6,
  },
  activeTabText: { color: COLORS.white },
  mapOptions: {
    position: 'absolute',
    top: Platform.OS === 'ios' ? 210 : 170,
    right: 15,
    zIndex: 100,
    alignItems: 'center',
  },
  optionBtn: {
    backgroundColor: COLORS.white,
    width: 44, height: 44,
    borderRadius: 22,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 10,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 5,
  },
  bottomControls: {
    position: 'absolute',
    bottom: 30,
    left: 0, right: 0,
    zIndex: 100,
    elevation: 10,
  },
  filterScroll: { paddingHorizontal: 15, marginBottom: 8 },
  filterChip: {
    backgroundColor: COLORS.white,
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 20,
    marginRight: 8,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.06,
    shadowRadius: 3,
    elevation: 2,
    flexDirection: 'row',
    alignItems: 'center',
  },
  activeFilterChip: { backgroundColor: COLORS.primary },
  filterText: { fontSize: 12, fontWeight: '600', color: COLORS.textSecondary },
  activeFilterText: { color: COLORS.white },
  statusChip: {
    backgroundColor: COLORS.white,
    paddingHorizontal: 12,
    paddingVertical: 7,
    borderRadius: 20,
    marginRight: 8,
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: COLORS.border,
    elevation: 2,
  },
  statusDot: { width: 8, height: 8, borderRadius: 4, marginRight: 6 },
  modalBg: { flex: 1, backgroundColor: COLORS.overlay, justifyContent: 'flex-end' },
  modalContent: {
    backgroundColor: COLORS.white,
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    padding: 20,
    maxHeight: height * 0.7,
  },
  modalClose: {
    position: 'absolute',
    top: 12, right: 15,
    zIndex: 5,
    padding: 5,
  },
  modalCloseText: { fontSize: 22, color: COLORS.textSecondary, fontWeight: 'bold' },
  modalTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    marginBottom: 15,
    color: COLORS.primary,
  },
  modalImage: {
    width: '100%',
    height: 150,
    borderRadius: 10,
    marginBottom: 15,
    backgroundColor: COLORS.border,
  },
  infoRow: { flexDirection: 'row', alignItems: 'center', marginBottom: 8 },
  infoLabel: { fontWeight: 'bold', width: 80, fontSize: 14, color: COLORS.text },
  infoValue: { fontSize: 14, color: COLORS.textSecondary, flex: 1 },
  modalBtn: {
    backgroundColor: COLORS.secondary,
    padding: 15,
    borderRadius: 10,
    alignItems: 'center',
    marginTop: 20,
  },
  modalBtnText: { color: COLORS.white, fontWeight: 'bold', fontSize: 16 },
  markerSignalement: {
    padding: 6,
    borderRadius: 18,
    borderWidth: 2,
    borderColor: COLORS.white,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
    elevation: 4,
  },
  markerDot: { width: 10, height: 10, borderRadius: 5 },
  markerPanel: {
    width: 30, height: 30,
    borderRadius: 15,
    backgroundColor: COLORS.white,
    borderWidth: 2,
    justifyContent: 'center',
    alignItems: 'center',
    elevation: 5,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
  },
  markerPanelInner: { width: 20, height: 20, borderRadius: 10, justifyContent: 'center', alignItems: 'center' },
  panelIcon: { fontSize: 12, color: COLORS.white, fontWeight: 'bold' },
  calloutCard: {
    width: 230,
    backgroundColor: COLORS.white,
    borderRadius: 15,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: COLORS.border,
  },
  calloutHeader: { padding: 10, alignItems: 'center' },
  calloutTitle: { color: COLORS.white, fontWeight: 'bold', fontSize: 13 },
  calloutBody: { padding: 12 },
  calloutDesc: { fontSize: 13, color: COLORS.text, marginBottom: 8, lineHeight: 18 },
  calloutDate: { fontSize: 11, color: COLORS.textTertiary, textAlign: 'right' },
  emptyFilterText: { textAlign: 'center', color: COLORS.textSecondary, padding: 10, fontSize: 13 },
  villeBtn: {
    position: 'absolute',
    top: Platform.OS === 'ios' ? 155 : 115,
    right: 15,
    zIndex: 150,
    backgroundColor: COLORS.white,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 20,
    flexDirection: 'row',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.08,
    shadowRadius: 4,
    elevation: 5,
  },
  villeBtnText: { fontSize: 12, fontWeight: '700', color: COLORS.primary, marginLeft: 5 },
});
